import React from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'

interface Props {
    children?: React.ReactNode
}

const Layout = ({ children }: Props) => {
  return (
    <div>
        <Head>
            <title>Track Daily</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header>
            <Navbar/>
        </header>
        <main>
            {children}    
        </main>
        <footer>
            {/* <Footer/> */}
        </footer>
    </div>
  )
}

export default Layout